apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nodeapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template: 
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "3000"
        dapr.io/config: "pipeline" # "pipeline" é o nome do "Configuration" criado
    spec:
      containers:
      - name: node
        image: ocimar/oauth2node
        ports:
        - containerPort: 3000
