apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template: 
    metadata:
      labels:
        app: frontend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frontendapp"
        dapr.io/app-port: "8080"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: frontend
        image: dapriosamples/distributed-calculator-react-calculator:latest
        ports:
        - containerPort: 8080