apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: awssecretmanager
  namespace: default
spec:
  type: secretstores.aws.secretmanager
  version: v1
  metadata:
  - name: region
    value: "us-east-2"
  - name: accessKey
    secretKeyRef:
      name: aws-secret
      key:  ACCESS_KEY
  - name: secretKey
    secretKeyRef:
      name: aws-secret
      key:  SECRET_KEY