apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: a-subscriptions
spec:
  topic: A
  route: /A
  pubsubname: pubsub
scopes:
- python-subscriber
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: c-subscriptions
spec:
  topic: C
  route: /C
  pubsubname: pubsub
scopes:
- python-subscriber