apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template: 
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: node
        image: ocimar/nodeapp
        ports:
          - containerPort: 3000